language: rust
cache: cargo
sudo: required

branches:
  only:
  - master

os:
  - linux
  - windows
  - osx

rust:
  - stable
  - nightly

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - libbfd-dev
      - binutils-dev
      - libiberty-dev

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

install:
  - if [[ $TRAVIS_RUST_VERSION == "stable" ]]; then rustup component add rustfmt; fi
  - if [[ $TRAVIS_RUST_VERSION == "stable" ]]; then rustup component add clippy; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then pip install six; fi

before_script:
  - export PATH=/usr/bin/:$HOME/.cargo/bin:$PATH

script:
  - if [[ $TRAVIS_RUST_VERSION == "stable" ]]; then cargo fmt -- --check; fi
  - if [[ $TRAVIS_RUST_VERSION == "stable" ]]; then cargo clippy --all; fi
  - cargo build --verbose --all
  - cargo test --verbose --all

env:
  global:
    - RUST_BACKTRACE=1
