[package]
name = "okchain-rust-sdk"
version = "0.1.0"
authors = ["zjhsdtc <zjhsdtc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
